clone working

diff --git a/bin/p4b_update b/bin/p4b_update
--- a/bin/p4b_update
+++ b/bin/p4b_update
@@ -1,27 +1,19 @@
 #!/bin/bash
+P4BRIDGEDIR=.p4bridge
+if [ ! -d "$P4BRIDGEDIR" ]
+then
+    echo "missing $P4BRIDGEDIR"
+    exit 1
+fi
+. p4b_setdepot
 
-OPENED=`p4 opened | wc -l`
+OPENED=`p4 opened 2>/dev/null | wc -l`
 if [ ! $OPENED -eq 0 ]
 then
 	echo "open files in perforce, please revert or shelve first"
 	exit 1
 fi
-
-pushd .
-cd $P4BRIDGE_HOME 
-
-if [ $# -gt 0 ]
-then
-	for repo in $*
-	do
-		export GIT_DIR=$repo/.git 
-		p4b_helperupdate
-	done
-else
-	cat .repos | xargs -L1 echo | gawk '{
-			repo=$1
-			system("export GIT_DIR="repo"/.git ; p4b_helperupdate")
-			}'
-fi
-popd
-repo sync
+CURR_BRANCH=master
+git checkout p4_master && p4b_availchanges `lastp4change` | xargs -L1 p4b_getupdate
+git checkout .
+git checkout $CURR_BRANCH
